### ISSUE TITLE
Question about SMPL

### ISSUE THREAD

**Issue by Golriz-code** [liren2515/DrapeNet#1]
Hello,
Thank you for your great work.
I did not understand exactly where we should use SMPL model.
In readme i found this , but i could not find the pretrained model in the link.
 "Download the female  from http://smplify.is.tue.mpg.de/ and place basicModel_f_lbs_10_207_0_v1.0.0.pkl in the folder of ./smpl_pytorch."

**Comment by liren2515** [comment]
Hello,

You need to register on http://smplify.is.tue.mpg.de/, and then download the SMPL models from it.

**Comment by Golriz-code** [comment]
Thank you for your help,
I have successfully trained the network, but I am currently experiencing an issue with the export_mesh.py script. It's worth mentioning that I pre-processed my data using your provided code. However, when attempting to export the mesh, I encountered an error indicating "surface not found!" on some occasions, and "Cuda out of memory!" on others. I would greatly appreciate any suggestions or guidance you can provide to help resolve these problems.

**Comment by liren2515** [comment]
"surface not found!" usually happens when you use a very small resolution for meshing or your object is too small to be reconstructed by marching cubes. Another potential reason can be your network is not well trained.  

For "Cuda out of memory!", I guess your resolution is too large this time and you don't have enough GPU memory for meshing.

**Comment by Golriz-code** [comment]
Thank you for your answer. I have successfully trained the encdec.py model using my own dataset. However, when I try to export_meshes, I consistently encounter an error stating "surface not found". It is important to mention that I preprocess my data using preprocess_udf.py. Regarding your previous comment about using a small resolution for meshing, I have not made any changes to the configuration file or the code. I have also attempted to upscale my data, but I still encounter the same error of "No surface found!". I would like to know if I need to normalize the data or if the issue lies elsewhere. Do you have any suggestions for me?

**Comment by liren2515** [comment]
We normalize the mesh to be within the range of [-1, 1]. How do you normalize your data?

**Comment by Golriz-code** [comment]
Thank you for your response. After reviewing the garment data, I noticed that it does not fall within the range of [-1, 1]. Additionally, the meshes are not centered around the center of mass. Since I am using my own dataset, I would appreciate guidance on the necessary transformations that need to be applied.

I would also like to know whether the normalization should be dataset-based or raw-based. Should each mesh be normalized individually, or should all meshes be normalized together as a whole?

**Comment by liren2515** [comment]
The garments we use are already within the range of [-1, 1], since they are draped on the t-posed SMPL body with neutral shape.  So we don't need to normalize them. 

If you want to normalize your data, I think both the dataset-based and the raw-based ways should work. They won't have too much influence for the training.
