### ISSUE TITLE
fitting 3D scans

### ISSUE THREAD

**Issue by chenbomath** [liren2515/DrapeNet#4]
Hi, your paper mentioning that it can fit 3D scans and 2D images,
could you provide an example of fitting 3D scans? Thanks

**Comment by liren2515** [comment]
Hello, we don't plan to release the codes for fitting. The fitting process is similar to the one in [DIG](https://github.com/liren2515/DIG), and you can find some necessary codes from [here](https://github.com/liren2515/DIG/issues/4). You need to replace the SDF with UDF and use the draping functions in this repo to deform it.

**Comment by chenbomath** [comment]
Thank you.

**Comment by simonschoenhofen** [comment]
Hey! 

Thanks for this great Repo and Paper! 

> he fitting process is similar to the one in [DIG](https://github.com/liren2515/DIG), and you can find some necessary codes from https://github.com/liren2515/DIG/issues/4.

With the use of the issue the linked issues, I was able to recreate a fitting! However, It is not perfect since I currently estimate the camera position of the renderer with a fitting in pytorch3d to the SMPL mesh silhouette. This is sometimes way off.

May I ask how did you get the camera position for your renderer?

**Comment by liren2515** [comment]
When you have a 3D scan, you need to first align the mesh to it. To this end, we first optimize the smpl parameters and an offset parameter $(\delta_x, \delta_y, \delta_z)$. After that, we optimize the garment parameter. 

For 2D images, the camera parameters are estimated from the smpl pose estimator (e.g. FrankMocap).
